[package]
name = "mysqltest"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
mysql_async = {version = "0.36.1", features = ["binlog"]}
mysql_common = "0.35.5"
tokio = {version = "1.47.1", features = ["full"]}
tokio-stream = "0.1.17"
