[mysql]
host = "localhost"
user = "root"
pass = "123456"
port = 4406
# max_allowed_packet = 67108864
# start_position = 4
# start_filename = ""
# init_sql=[]

[replica]
replica_id = 5000
replica_uuid = "79a87595-66fe-42cd-b235-e686346fbfc0"
report_port = 8527
report_host = "mysql-avatar"
datadir = "./data"

# Relay Log Section
# Default Value: datadir + '/' + 'relay-bin'
relay_log_basename = "./data/relay-bin/"
relay_log = "relay-bin"
relay_log_index = "relay-bin.index"
# Unused.
relay_log_purge = 1
# Unused.
relay_log_recovery = 1

# 
rpl_semi_sync_replica_enabled = 1
# Unused.
replica_max_allowed_packet = 1024
replica_verify_checksum = 1
# 
skip_event = [ 0x04 ]